# Step 1: Use an official Go image as a build environment
FROM golang:1.20 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app for Linux architecture
RUN GOOS=linux GOARCH=amd64 go build -o server .

# Step 2: Use the same Go image for the final container
FROM golang:1.20

# Set the working directory inside the container
WORKDIR /app

# Copy the binary built in the previous stage
COPY --from=builder /app/server .


COPY .env .

# Expose the port on which the server will run
EXPOSE 8080

# Command to run the executable
CMD ["./server"]
