version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: codedb
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/  # Mount init-scripts directory

  go-server:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/codedb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
